# Generated by Django 4.1.6 on 2023-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_file', models.FileField(upload_to='default_video/')),
                ('convert_video', models.FileField(upload_to='convert_video/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
